### ISSUE TITLE
Метод не найдено

### ISSUE THREAD

**Issue by Maxmudjon** [skysilver-lab/majordomo-xiaomimiio#6]
![image](https://user-images.githubusercontent.com/23142922/48593411-8ad9bd00-e96e-11e8-8b0a-1f7ce26ddebc.png)

**Comment by Maxmudjon** [comment]
Я не могу получит список радиостанция

**Comment by Maxmudjon** [comment]
всё получилось!
"get_channels", {"start": 0}

**Comment by skysilver-lab** [comment]
Привет. Дополню.
Если станций больше 10, то нужно повторно слать команду, увеличивая start на 10.
"get_channels", {"start": 10}
"get_channels", {"start": 20}
и т. д.
