### ISSUE TITLE
добавление deerma.humidifier.jsq

### ISSUE THREAD

**Issue by solalex1** [skysilver-lab/majordomo-xiaomimiio#9]
Большая просьба добавить профиль для Mi Smart Sterilization Humidifier

**Comment by skysilver-lab** [comment]
В версии 3.2 добавлено.

**Comment by solalex1** [comment]
Работает!

**Comment by eduard5000** [comment]
Добрый вечер. Планируете дабавить данное устройство в модуль? deerma.humidifier.jsq5
 Mi Smart Sterilization Humidifier.
